# VideoClub con Seguridad

###
# @name keycloak get token (web angular react)
POST http://{{host}}:9090/realms/videoclub/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = web &
username = usuarioadmin &
password = usuarioadmin &
grant_type = password &
scope = openid

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("access_token", response.body.access_token);
    });
%}

###
# @name keycloak get token (api)
POST http://{{host}}:9090/realms/videoclub/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = test-api &
client_secret = dstNSsANvqlaGfZCJa1mcYzP1EBAYP4N &
grant_type = client_credentials &
scope = openid test
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("access_token_api", response.body.access_token);
    });
%}

###
# @name api List get (with login and admin Role)
GET http://{{host}}:8080/tests
Authorization: Bearer {{access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name api List get (with login and admin Role)
GET http://{{host}}:9500/catalogo/tests
Authorization: Bearer {{access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


###
# @name actuator health
GET http://{{host}}:8080/metrics/health

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


###
# @name api docs
GET http://{{host}}:8080/api-docs

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

